### ISSUE TITLE
mockDeep From Another Package

### ISSUE THREAD

**Issue by EricFiori** [eratio08/vitest-mock-extended#158]
I'm attempting to mock a prisma client using mock deep following this tutorial: https://www.prisma.io/blog/testing-series-1-8eRB5p0Y8o/. 

In our case we have a package called 'database' that exports the prisma clients. This is separate from the package that's using them in a vitest test.

I've tried several ways to get this to work. At present I have my __mocks__  (double underscore before and after) folder under the /package/database/dist/ folder.
Based on stepping through the vitest-mock-extended source, this is where the __mocks__ folder is expected to be based on the following:

`vi.mock('database');`

However, when I run the test, I get the following:

```
Error: No "exports" main defined in C:\projects\web\node_modules\vitest-mock-extended\package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:612:7)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\projects\web\packages\database\src\__mocks__\index.ts:7:1)
```

I have tried removing node_modules, package-lock.json and re-running npm install to no avail.

```
  npm: '8.19.2',
  node: '18.12.1',
  "vitest": "^0.29.2",
  "vitest-mock-extended": "^1.1.0"
```

Anyone have ideas? I'm stumped and would really like to get this working.

Thanks,
Eric

**Comment by eratio08** [comment]
Hey eric, could you provide a minimal project to reproduce it? You could also create a pr with a subfolder containing this project so I can have a look/debug it?

**Comment by EricFiori** [comment]
Here's a [Project](https://github.com/EricFiori/prisma-deepmock-monorepo) that exhibits the issue I'm having.

To get it running you should be able to npm install, then  npm run build in database and api, as well as npm run db:generate in database.

Then I usually run the test from webstorm's play button, but vitest --run should also reproduce the issue.

For sanity checking, I have commented out a 'manual' mock of the desired object in the test file. This can replace the vi.mock('database') line and the mocking process works as desired, except without the use of deepMock.

Thanks,
Eric

**Comment by eratio08** [comment]
Thanks, great! I will have a look and see if I can figure out whats wrong.

**Comment by eratio08** [comment]
Sound like I did not properly define the expected [exports](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#exports). Looking into this.

**Comment by eratio08** [comment]
Ahh ok found it. This was all due to `tsconfig/node.json`
```json 
{
...
   "compilerOptions": {
    ...
    "module": "CommonJS",
    ...
  },
}
```
it should be
```json 
{
...
   "compilerOptions": {
    ...
    "module": "ES2022",
    ...
  },
}
```

**Comment by EricFiori** [comment]
That helped get past the error! Thanks for your assistance! 

Also, based on that change and the state of the repo - would you expect the prisma client to be mocked correctly in src/prisma.ts? I'm getting the following error when I attempt to run the test, expecting that prisma is deep mocked at this point, but it appears to just be undefined:

TypeError: Cannot read properties of undefined (reading 'queue')
    at Module.addQueueItem (C:\workspace\prisma-deepmock-monorepo\apps\api\src\prisma.ts:7:34)

Thanks,
Eric

**Comment by eratio08** [comment]
On my end is does not seem to be null, this is the queue object on my end. I added a console log into the `prisma.ts`. The stout is from running `npx vitest run`
<img width="507" alt="image" src="https://user-images.githubusercontent.com/5063643/226742536-89517464-d276-462f-b6ae-18deefe21e52.png">

There might be a slight change in the setup on my side.

**Comment by EricFiori** [comment]
Do you know what config you might have changed? 

Thanks,
Eric

**Comment by eratio08** [comment]
```diff
diff --git a/apps/api/package.json b/apps/api/package.json
index a629093..ceaa1ee 100644
--- a/apps/api/package.json
+++ b/apps/api/package.json
@@ -1,22 +1,22 @@
 {
-	"name": "api",
-	"version": "1.0.0",
-	"description": "test",
-	"main": "src/server.ts",
-	"scripts": {
-		"build": "tsc"
-	},
-	"keywords": [],
-	"dependencies": {
-		"database": "*",
-		"dotenv": "^16.0.0"
-	},
-	"devDependencies": {
-		"@types/node": "^16.11.7",
-		"@types/supertest": "^2.0.12",
-		"tsconfig": "*",
-		"typescript": "4.9.5",
-		"vitest": "^0.29.2",
-		"vitest-mock-extended": "^1.1.0"
-	}
+  "name": "api",
+  "version": "1.0.0",
+  "description": "test",
+  "main": "src/server.ts",
+  "scripts": {
+    "build": "tsc"
+  },
+  "keywords": [],
+  "dependencies": {
+    "database": "*",
+    "dotenv": "^16.0.0"
+  },
+  "devDependencies": {
+    "@types/node": "^16.11.7",
+    "@types/supertest": "^2.0.12",
+    "tsconfig": "*",
+    "typescript": "4.9.5",
+    "vitest": "^0.29.2",
+    "vitest-mock-extended": "^1.1.3"
+  }
 }
diff --git a/apps/api/src/prisma.ts b/apps/api/src/prisma.ts
index 8742dfd..7b611c2 100644
--- a/apps/api/src/prisma.ts
+++ b/apps/api/src/prisma.ts
@@ -1,19 +1,19 @@
-import {prisma} from 'database';
+import { prisma } from 'database';
 
-export const addQueueItem = async  (item:any) => {
+export const addQueueItem = async (item: any) => {
+  const jsonData = JSON.stringify(item);
+  const queueItem = await prisma.queue.create({
+    data: {
+      type: 'test',
+      destination: 'test',
+      status: 'pending',
+      status_date: new Date(),
+      payload: jsonData,
+      add_date: new Date(),
+    },
+  });
 
-		const jsonData = JSON.stringify(item);
-
-		const queueItem = await prisma.queue.create({
-			data: {
-				type: 'test',
-				destination: 'test',
-				status: 'pending',
-				status_date: new Date(),
-				payload: jsonData,
-				add_date: new Date()
-			}
-		});
-		return queueItem;
-}
+  console.log(prisma.queue);
 
+  return queueItem;
+};
diff --git a/apps/api/test/prisma.mock.test.ts b/apps/api/test/prisma.mock.test.ts
index ca4df72..c61e8b4 100644
--- a/apps/api/test/prisma.mock.test.ts
+++ b/apps/api/test/prisma.mock.test.ts
@@ -40,16 +40,14 @@ vi.mock('database');
 // 	}
 // );
 
-describe("testing mocks", () => {
-	test('test mock', async () => {
-		const data =  {
-				firstname: 'test',
-				lastname: 'user'
-			};
+describe('testing mocks', () => {
+  test('test mock', async () => {
+    const data = {
+      firstname: 'test',
+      lastname: 'user',
+    };
 
-		const val :any = await addQueueItem(data);
-		expect(val.id).toBe(55);
-	});
+    const val: any = await addQueueItem(data);
+    expect(val.id).toBe(55);
+  });
 });
-
-
diff --git a/apps/api/tsconfig.json b/apps/api/tsconfig.json
index bb6cc86..39d6d81 100644
--- a/apps/api/tsconfig.json
+++ b/apps/api/tsconfig.json
@@ -1,9 +1,9 @@
 {
-	"extends": "tsconfig/node.json",
-	"compilerOptions": {
-		"rootDir": "src",
-		"outDir": "dist"
-	},
-	"include": ["src"],
-  	"strictNullChecks":false
+  "extends": "tsconfig/node.json",
+  "compilerOptions": {
+    "rootDir": "src",
+    "outDir": "dist",
+    "strictNullChecks": false
+  },
+  "include": ["src"]
 }
diff --git a/apps/api/vitest.config.ts b/apps/api/vitest.config.ts
index 5cc8703..0a3dcdc 100644
--- a/apps/api/vitest.config.ts
+++ b/apps/api/vitest.config.ts
@@ -1,10 +1,10 @@
 /// <reference types="vitest" />
 
-import { defineConfig } from "vitest/config";
+import { defineConfig } from 'vitest/config';
 
 export default defineConfig({
-	test: {
-		globals: true,
-		env: { "NODE_ENV": "test"},
-	},
+  test: {
+    globals: true,
+    env: { NODE_ENV: 'test' },
+  },
 });
diff --git a/package.json b/package.json
index e7fa524..8ef8a3c 100644
--- a/package.json
+++ b/package.json
@@ -1,16 +1,11 @@
 {
-	"name": "prisma-deepmock-monorepo",
-	"version": "0.0.0",
-	"private": true,
-	"workspaces": [
-		"apps/*",
-		"packages/*"
-	],
-	"scripts": {
-
-	},
-	"engines": {
-		"node": ">=18.0.0"
-	},
-	"packageManager": "npm@8.13.2"
+  "name": "prisma-deepmock-monorepo",
+  "private": true,
+  "workspaces": [
+    "apps/*",
+    "packages/*"
+  ],
+  "engines": {
+    "node": ">=18.0.0"
+  }
 }
diff --git a/packages/database/package.json b/packages/database/package.json
index 8e8429b..61e0c6a 100644
--- a/packages/database/package.json
+++ b/packages/database/package.json
@@ -1,24 +1,26 @@
 {
-	"name": "database",
-	"version": "1.0.0",
-	"main": "./dist/index.js",
-	"types": "./dist/index.d.ts",
-	"files": [
-		"dist/**"
-	],
-	"scripts": {
-		"build": "tsc",
-		"dev": "tsc --watch",
-		"db:generate": "node scripts/generateClients.js"
-	},
-	"dependencies": {
-		"@prisma/client": "^4.11.0",
-		"@prisma/instrumentation": "^4.11.0"
-	},
-	"devDependencies": {
-		"prisma": "^4.11.0",
-		"tsconfig": "*",
-		"typescript": "^4.8.3",
-		"vitest-mock-extended": "^1.1.0"
-	}
+  "name": "database",
+  "version": "1.0.0",
+  "main": "./dist/index.js",
+  "types": "./dist/index.d.ts",
+  "module": "./dist/index.js",
+  "files": [
+    "dist/**"
+  ],
+  "scripts": {
+    "build": "tsc",
+    "dev": "tsc --watch",
+    "db:generate": "node scripts/generateClients.js"
+  },
+  "dependencies": {
+    "@prisma/client": "^4.11.0",
+    "@prisma/instrumentation": "^4.11.0"
+  },
+  "devDependencies": {
+    "prisma": "^4.11.0",
+    "tsconfig": "*",
+    "typescript": "^4.8.3",
+    "vitest": "^0.29.3",
+    "vitest-mock-extended": "^1.1.3"
+  }
 }
diff --git a/packages/database/src/__mocks__/client.js b/packages/database/src/__mocks__/client.js
deleted file mode 100644
index d083d6e..0000000
--- a/packages/database/src/__mocks__/client.js
+++ /dev/null
@@ -1,10 +0,0 @@
-"use strict";
-exports.__esModule = true;
-//import { hubspot } from "../client";
-var vitest_1 = require("vitest");
-var vitest_mock_extended_1 = require("vitest-mock-extended");
-(0, vitest_1.beforeEach)(function () {
-    (0, vitest_mock_extended_1.mockReset)(hubspot);
-});
-var hubspot = (0, vitest_mock_extended_1.mockDeep)();
-exports["default"] = hubspot;
diff --git a/packages/database/src/__mocks__/client.ts b/packages/database/src/__mocks__/client.ts
index 8acfe10..f330ed1 100644
--- a/packages/database/src/__mocks__/client.ts
+++ b/packages/database/src/__mocks__/client.ts
@@ -1,11 +1,10 @@
-import { PrismaClient as Prisma } from "database/prisma/generated/Prisma";
+import { PrismaClient as Prisma } from 'database/prisma/generated/Prisma';
 import { beforeEach } from 'vitest';
-import { mockDeep, mockReset } from "vitest-mock-extended";
+import { mockDeep, mockReset } from 'vitest-mock-extended';
 
+const prisma = mockDeep<Prisma>();
 beforeEach(() => {
-	mockReset(prisma);
+  mockReset(prisma);
 });
 
-const prisma = mockDeep<Prisma>();
-export default prisma;
-
+export { prisma };
diff --git a/packages/database/src/__mocks__/index.js b/packages/database/src/__mocks__/index.js
deleted file mode 100644
index d083d6e..0000000
--- a/packages/database/src/__mocks__/index.js
+++ /dev/null
@@ -1,10 +0,0 @@
-"use strict";
-exports.__esModule = true;
-//import { hubspot } from "../client";
-var vitest_1 = require("vitest");
-var vitest_mock_extended_1 = require("vitest-mock-extended");
-(0, vitest_1.beforeEach)(function () {
-    (0, vitest_mock_extended_1.mockReset)(hubspot);
-});
-var hubspot = (0, vitest_mock_extended_1.mockDeep)();
-exports["default"] = hubspot;
diff --git a/packages/database/src/__mocks__/index.ts b/packages/database/src/__mocks__/index.ts
index 5ec7692..4f1cce4 100644
--- a/packages/database/src/__mocks__/index.ts
+++ b/packages/database/src/__mocks__/index.ts
@@ -1 +1 @@
-export * from "./client";
+export * from './client';
diff --git a/packages/database/src/client.js b/packages/database/src/client.js
deleted file mode 100644
index cd121d6..0000000
--- a/packages/database/src/client.js
+++ /dev/null
@@ -1,59 +0,0 @@
-"use strict";
-exports.__esModule = true;
-exports.hubspot = exports.graphics = exports.pressop = exports.slack = exports.catalog = exports.wtw = exports.mydata = exports.intranet = exports.generaldata = void 0;
-var GeneralData_1 = require("../prisma/generated/GeneralData");
-var Intranet_1 = require("../prisma/generated/Intranet");
-var MyData_1 = require("../prisma/generated/MyData");
-var WTW_1 = require("../prisma/generated/WTW");
-var Catalog_1 = require("../prisma/generated/Catalog");
-var Slack_1 = require("../prisma/generated/Slack");
-var Pressop_1 = require("../prisma/generated/Pressop");
-var Graphics_1 = require("../prisma/generated/Graphics");
-var Hubspot_1 = require("../prisma/generated/Hubspot");
-var optionsArgs = {};
-if (process.env.NODE_ENV == "development") {
-    optionsArgs["log"] = ["error", "warn", "query"];
-}
-// Creates new prisma database objects if not already defined, otherwise uses already defined objects
-/**
- * Prisma client for the GeneralData database
- */
-var generaldata = new GeneralData_1.PrismaClient(optionsArgs);
-exports.generaldata = generaldata;
-/**
- * Prisma client for the Intranet database
- */
-var intranet = new Intranet_1.PrismaClient(optionsArgs);
-exports.intranet = intranet;
-/**
- * Prisma client for the MyData database
- */
-var mydata = new MyData_1.PrismaClient(optionsArgs);
-exports.mydata = mydata;
-/**
- * Prisma client for the WTW database
- */
-var wtw = new WTW_1.PrismaClient(optionsArgs);
-exports.wtw = wtw;
-/**
- * Prisma client for the Catalog database
- */
-var catalog = new Catalog_1.PrismaClient(optionsArgs);
-exports.catalog = catalog;
-/**
- * Prisma client for the Slack database
- */
-var slack = new Slack_1.PrismaClient(optionsArgs);
-exports.slack = slack;
-/**
- * Prisma client for the Pressop database
- */
-var pressop = new Pressop_1.PrismaClient(optionsArgs);
-exports.pressop = pressop;
-/**
- * Prisma client for the Graphics database
- */
-var graphics = new Graphics_1.PrismaClient(optionsArgs);
-exports.graphics = graphics;
-var hubspot = new Hubspot_1.PrismaClient(optionsArgs);
-exports.hubspot = hubspot;
diff --git a/packages/database/src/client.ts b/packages/database/src/client.ts
index 0f66afe..dbefedc 100644
--- a/packages/database/src/client.ts
+++ b/packages/database/src/client.ts
@@ -1,23 +1,22 @@
-import { PrismaClient as Prisma } from "../prisma/generated/Prisma";
+import { PrismaClient as Prisma } from '../prisma/generated/Prisma';
 
-
-type LogLevel = "info" | "query" | "warn" | "error";
+type LogLevel = 'info' | 'query' | 'warn' | 'error';
 type LogDefinition = {
-	level: LogLevel;
-	emit: "stdout" | "event";
+  level: LogLevel;
+  emit: 'stdout' | 'event';
 };
-type ErrorFormat = "pretty" | "colorless" | "minimal";
+type ErrorFormat = 'pretty' | 'colorless' | 'minimal';
 interface PrismaClientOptions {
-	errorFormat?: ErrorFormat;
-	log?: (LogLevel | LogDefinition)[];
+  errorFormat?: ErrorFormat;
+  log?: (LogLevel | LogDefinition)[];
 }
 
 const optionsArgs: PrismaClientOptions = {};
 
-if (process.env.NODE_ENV == "development") {
-	optionsArgs["log"] = ["error","warn","query"];
+if (process.env.NODE_ENV == 'development') {
+  optionsArgs['log'] = ['error', 'warn', 'query'];
 }
 
 const prisma = new Prisma(optionsArgs);
 
-export {  prisma};
+export { prisma };
diff --git a/packages/database/src/index.ts b/packages/database/src/index.ts
index 5ec7692..4f1cce4 100644
--- a/packages/database/src/index.ts
+++ b/packages/database/src/index.ts
@@ -1 +1 @@
-export * from "./client";
+export * from './client';
diff --git a/packages/database/tsconfig.json b/packages/database/tsconfig.json
index 3e1828f..957e322 100644
--- a/packages/database/tsconfig.json
+++ b/packages/database/tsconfig.json
@@ -1,9 +1,10 @@
 {
-	"extends": "tsconfig/node.json",
-	"compilerOptions": {
-		"outDir": "dist"
-	},
-	"include": ["./src/index.ts", "./src/__mocks__/index.ts"],
-	"exclude": ["node_modules"],
-  "strictNullChecks":false
+  "extends": "tsconfig/node.json",
+  "compilerOptions": {
+    "outDir": "dist",
+    "declaration": true,
+    "strictNullChecks": false
+  },
+  "include": ["./src/index.ts", "./src/__mocks__/index.ts"],
+  "exclude": ["node_modules"]
 }
diff --git a/packages/tsconfig/base.json b/packages/tsconfig/base.json
index 541110c..cd01776 100644
--- a/packages/tsconfig/base.json
+++ b/packages/tsconfig/base.json
@@ -1,23 +1,21 @@
 {
-	"$schema": "https://json.schemastore.org/tsconfig",
-	"compilerOptions": {
-		"moduleResolution": "node",
-		"isolatedModules": true,
-		"resolveJsonModule": true,
-		"declaration": true,
-		"declarationMap": true,
-		"composite": false,
-		"allowJs": true,
-		"sourceMap": true,
-		"inlineSources": false,
-		"esModuleInterop": true,
-		"skipLibCheck": true,
-		"forceConsistentCasingInFileNames": true,
-		"strict": true,
-		"noUncheckedIndexedAccess": true,
-		"noImplicitAny": true
-	},
-	"exclude": [
-		"node_modules"
-	]
+  "$schema": "https://json.schemastore.org/tsconfig",
+  "compilerOptions": {
+    "moduleResolution": "nodenext",
+    "isolatedModules": true,
+    "resolveJsonModule": true,
+    "declaration": true,
+    "declarationMap": true,
+    "composite": false,
+    "allowJs": true,
+    "sourceMap": true,
+    "inlineSources": false,
+    "esModuleInterop": true,
+    "skipLibCheck": true,
+    "forceConsistentCasingInFileNames": true,
+    "strict": true,
+    "noUncheckedIndexedAccess": true,
+    "noImplicitAny": true
+  },
+  "exclude": ["node_modules"]
 }
diff --git a/packages/tsconfig/node.json b/packages/tsconfig/node.json
index 4dbe2f1..ab01d51 100644
--- a/packages/tsconfig/node.json
+++ b/packages/tsconfig/node.json
@@ -1,17 +1,13 @@
 {
-	"$schema": "https://json.schemastore.org/tsconfig",
-	"extends": "./base.json",
-	"compilerOptions": {
-		"target": "ES2022",
-		"module": "CommonJS",
-		"checkJs": true,
-		"removeComments": true,
-		"esModuleInterop": true
-	},
-	"include": [
-		"src"
-	],
-	"exclude": [
-		"node_modules"
-	]
+  "$schema": "https://json.schemastore.org/tsconfig",
+  "extends": "./base.json",
+  "compilerOptions": {
+    "target": "ES2022",
+    "module": "ES2022",
+    "checkJs": true,
+    "removeComments": true,
+    "esModuleInterop": true
+  },
+  "include": ["src"],
+  "exclude": ["node_modules"]
 }

```
